# Generated by Django 4.2.8 on 2023-12-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_useralerts_useralert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=25),
        ),
    ]
